### ISSUE TITLE
Small enhancements

### ISSUE THREAD

**Issue by bgruening** [galaxyFlavorsGenerators/galaxyFlavorGenerator#13]
- [x] GALAXY_CONFIG_BRAND should be configurable
- [x] The user should be able to choose the Galaxy release
- [x] maybe a choosen repository should disappear from the search-box?
- [x] if you change the search term from `gemini` to `vcf` really quick the search will not be triggered
- [x] The search spinner looks a lot like a windows logo, can we just default to the Galaxy one?
- [x] "Your Galaxy will have the following:" should only appear if you have an item
- [x] "Repo" should be renamed to "Source Code"?
- [x] Linking to the TS would be nice

**Comment by doomedramen** [comment]
4: Why would you not want to re-search when the search term to changed?

**Comment by doomedramen** [comment]
3: Instead of showing `[added]`?

**Comment by bgruening** [comment]
> 4: Why would you not want to re-search when the search term to changed?

It was not re-searching. I guess the UI has a timeout and if you type fast the search is not triggered?

> 3: Instead of showing [added]?

This was more a discussion item, so thanks for bringing this up. Instead of the 'added' we could simply remove the item from the list and insert it back if we remove it if the user removes it from the bottom list.
I like this as well, just seeking for comments.

**Comment by doomedramen** [comment]
4: there is a 4 character minimum for searching, this is a limit of the TS API

3: I personally like the `added`, I would prefer to see things labeled as added than not see anything returned from the search because its already added, just avoids confusion.

**Comment by bgruening** [comment]
> 4: there is a 4 character minimum for searching, this is a limit of the TS API

Oh interesting, adding a whitespace works ;)

> 3: I personally like the `added`, I would prefer to see things labeled as added than not see anything returned from the search because its already added, just avoids confusion.

Ok, fair enough. Feel free to kill both of.
@martenson is there an API for filetype searches?

**Comment by martenson** [comment]
@bgruening what are filetype searches?

**Comment by bgruening** [comment]
@martenson give me all tools that can consume VCF files.

**Comment by martenson** [comment]
good idea, we are not there yet though :)

**Comment by doomedramen** [comment]
@jegalle 's pull adds release options but please see #18

**Comment by bgruening** [comment]
Great, all things are solved now.
