### ISSUE TITLE
BioJS integration

### ISSUE THREAD

**Issue by bgruening** [galaxyFlavorsGenerators/galaxyFlavorGenerator#2]
Query the BioJS registry for all visualisations that are tagged by `galaxy-vis`. These should be offered in addition to TS repositories, so that a user can drag on drop Visualisation in the `shopping cart`.

Visualisation can be installed into the Docker container with:

```
RUN install-biojs msa
```

So all what we need is the name of the vis in the BioJS registry.

**Comment by bgruening** [comment]
@jegalle do you want to work on this?

**Comment by jegalle** [comment]
Yes, I can work on this.

Will start to check how to query the biojs registry. Once we know that, the hardest part is done.

**Comment by bgruening** [comment]
@jegalle please have a look at https://github.com/biojs/biojs2galaxy this projects already queries the registry for all tools that can be converted to Galaxy

Thanks a lot!

**Comment by bgruening** [comment]
@jegalle any progress on this? I talked today to the BioJS guys and this would be really neat to have!

**Comment by jegalle** [comment]
Hi @bgruening

Start of the new academic year was very busy. Should have some more time now.
I started last week. I now have a way to get all galaxy visualisations in a json file via npm. There is no jsonp support on npmjs.com so this should become a cron job on the hosting server.

I'll look into the implementation part now, hopefully it will be implemented at the end of next week.

**Comment by bgruening** [comment]
Awesome! :)

**Comment by jegalle** [comment]
The work is done, let me know what you thing (pull request: #20 )

Preview of the changes: http://galaxyflavorgenerator.biobix.be/ (i'll take it off line as soon as the pull request is implemented.)

**Comment by bgruening** [comment]
The initial work was integrated with: https://github.com/galaxyFlavorsGenerators/galaxyFlavorGenerator/pull/21

**Comment by bgruening** [comment]
@jegalle did the initial integration, so I will close this.
I still have some Browser issues, but this can be tracked separately.
