### ISSUE TITLE
figure out how to leverage existing work

### ISSUE THREAD

**Issue by martenson** [galaxyFlavorsGenerators/galaxyFlavorGenerator#6]
we have 

https://github.com/jegalle/CustomGalaxyFlavors by @jegalle
https://github.com/wookoouk/galaxyFlavorGenerator by @wookoouk running at http://wookoouk.github.io/galaxyFlavorGenerator/

**Comment by bgruening** [comment]
I haven't heart from @jegalle. I suppose he is very busy.

**Comment by doomedramen** [comment]
I need to talk to you @martenson  before I can continue, hangouts|Skype?

**Comment by martenson** [comment]
@wookoouk I prefer async but if you want we can do a teleconference

**Comment by doomedramen** [comment]
just wanted a text chat to clear up some issues with the tool shed api, we should talk on here so its documented

**Comment by martenson** [comment]
as of today the Main Tool Shed has all the repos and tools indexed and available for searching at  /api/repositories and /api/tools

**Comment by doomedramen** [comment]
Thats great news, Ill add that now

**Comment by doomedramen** [comment]
can /api/repositories be queried for a specific tool id?

**Comment by martenson** [comment]
@wookoouk nope, what would be the usecase?

**Comment by doomedramen** [comment]
queried the tool api, now want to display the github info for that tool, would assume i would need to then query the repo api to get the info per tool

**Comment by martenson** [comment]
Should be addressed with https://github.com/galaxyFlavorsGenerators/galaxyFlavorGenerator/issues/7
If the need arises we can extend the toolsearch API to include more information.

**Comment by doomedramen** [comment]
That would be awesome :D

**Comment by doomedramen** [comment]
hmm, the repo name is not what I expected:

name:kraken_filter
repo_owner_name: cschu
repo_name: kraken_tools

name:kraken_combine
repo_owner_name: cschu
repo_name: kraken_tools

I do not have the unique info for using the `install-repository` tool as the current output is:
RUN install-repository \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o cschu --name kraken_tools" \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o cschu --name kraken_tools" \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o devteam --name kraken_translate" \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o devteam --name kraken" \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o devteam --name kraken_report" \ 
    "--url https://toolshed.g2.bx.psu.edu/ -o devteam --name kraken_report" \

**Comment by doomedramen** [comment]
example from search for 'kraken'
all 3 tools have the same repo_owner_username and repo_name

format:     name : repo_owner_username : repo_name

Kraken-translate : devteam : tool-data
Kraken-filter : devteam : tool-data
Kraken-mpa-report : devteam : tool-data

**Comment by doomedramen** [comment]
is repo_name incorrect?
@bgruening pointed out that for Kraken-filter the repo_name should be 'kraken_filter' (not 'tool-data')

**Comment by bgruening** [comment]
@martenson repo_name is not exposed correctly. The `name` is the tool-name or tool-id and the repo_name does not make sense to me.

**Comment by doomedramen** [comment]
Just checked, this is only an issue on MAIN TS,
Its fine on TEST TS

**Comment by bgruening** [comment]
Ha! Great, all what we need is an TS update! :)

**Comment by doomedramen** [comment]
forcing it to use TEST TS fixes the issue:

```
"--url https://testtoolshed.g2.bx.psu.edu/ -o cschu --name kraken_tools" \ 
"--url https://testtoolshed.g2.bx.psu.edu/ -o devteam --name kraken_translate" \ 
"--url https://testtoolshed.g2.bx.psu.edu/ -o devteam --name kraken" \ 
"--url https://testtoolshed.g2.bx.psu.edu/ -o devteam --name kraken_filter" \ 
"--url https://testtoolshed.g2.bx.psu.edu/ -o devteam --name kraken_report" \ 
```

**Comment by martenson** [comment]
there was older index on test (not broken yet) - thats why it worked

**Comment by doomedramen** [comment]
Searching for 'data_manager'
returns different things on MAIN and TEST

MAIN:
[{
  "times_downloaded": 707,
  "last_updated": "less than a month",
  "name": "data_manager",
  "approved": "no",
  "id": "2b6bab33b168bf9f",
  "homepage_url": null,
  "full_last_updated": "2015-07-08 05:07 PM",
  "repo_owner_username": "devteam",
  "long_description": "",
  "remote_repository_url": null,
  "description": "Builds sam indexes using the new data table format."
}, {
  "times_downloaded": 122,
  "last_updated": "less than a month",
  "name": "data_manager",
  "approved": "no",
  "id": "5316e9b4eb9a4965",
  "homepage_url": null,
  "full_last_updated": "2015-07-09 11:03 PM",
  "repo_owner_username": "iuc",
  "long_description": "Manage GEMINI databases. This tools will retrieve all files for the use in GEMINI.\r\n\r\nRepository-Maintainer: Björn Grüning\r\nRepository-Development: https://github.com/galaxy-iuc/tool_shed/",
  "remote_repository_url": null,
  "description": "Manage GEMINI annotation data"
}, {
  "times_downloaded": 74,
  "last_updated": "less than a month",
  "name": "data_manager",
  "approved": "no",
  "id": "1a540b81b0eb54a1",
  "homepage_url": null,
  "full_last_updated": "2015-07-15 11:05 PM",
  "repo_owner_username": "bgruening",
  "long_description": "",
  "remote_repository_url": null,
  "description": "Diamond data manager"
}]

The name does not seem correct

TEST

[{
  "times_downloaded": 205,
  "last_updated": "less than a year",
  "name": "data_manager",
  "approved": "no",
  "id": "acb3dc7f802404ed",
  "homepage_url": null,
  "full_last_updated": "2015-06-30 08:30 PM",
  "repo_owner_username": "blankenberg",
  "long_description": "data_manager_fetch_genome_all_fasta",
  "remote_repository_url": null,
  "description": "data_manager_fetch_genome_all_fasta"
}, {
  "times_downloaded": 55,
  "last_updated": "less than a month",
  "name": "data_manager",
  "approved": "no",
  "id": "160434ce3ad1f16a",
  "homepage_url": null,
  "full_last_updated": "2015-07-14 03:01 AM",
  "repo_owner_username": "devteam",
  "long_description": "data_manager_gatk_picard_index_builder",
  "remote_repository_url": null,
  "description": "data_manager_gatk_picard_index_builder"
}, {
  "times_downloaded": 61,
  "last_updated": "less than a month",
  "name": "data_manager",
  "approved": "no",
  "id": "911ca76da76707d7",
  "homepage_url": null,
  "full_last_updated": "2015-07-22 07:52 PM",
  "repo_owner_username": "jjohnson",
  "long_description": "faToTwoBit builds a 2bit index of a nucleic fasta file that can be used with blat and gfServer",
  "remote_repository_url": null,
  "description": "data_manager_ucsc_twobit_index_builder"
}]

the name still appears to be wrong, the description and long_description seem to be the correct name

**Comment by martenson** [comment]
MTS and TTS have different non-synchronized content - they are bound to give you different results.

The `name` will be fixed after https://github.com/galaxyproject/galaxy/pull/566 is merged and deployed.

**Comment by doomedramen** [comment]
awesome, thanks
name is the bit holding me back at the moment.

@martenson @bgruening which tool shed should I use for the flavor generator for now? TEST?

**Comment by martenson** [comment]
MTS, but give me 15mins to propagate the changes and rebuild the index

**Comment by doomedramen** [comment]
Cool, that output was from repo search BTW, tool search is no longer being
used for now

**Comment by martenson** [comment]
https://testtoolshed.g2.bx.psu.edu/api/repositories?q=kraken
https://testtoolshed.g2.bx.psu.edu/api/tools?q=kraken

proceeding with MTS

**Comment by doomedramen** [comment]
Great news, thanks for the quick turn around on this

**Comment by martenson** [comment]
MTS updated and regenerated, going for lunch

**Comment by doomedramen** [comment]
Looks good my end, now testing

**Comment by doomedramen** [comment]
Now leaving work for the day, push a demo of where I am up to: http://wookoouk.github.io/galaxyFlavorGenerator/

**Comment by bgruening** [comment]
Awesome, will test and report back!

**Comment by doomedramen** [comment]
The docker building many be broken...

**Comment by doomedramen** [comment]
The changes are:
Guthub links where available.
Moved from tool search to repo search.
Tooltips with description.
Better (still buggy) dockerfiles.
Started biojs registry search.

**Comment by bgruening** [comment]
This rocks! And the generated Dockerfile looks also good.
A few minor things I have seen so far! Many thanks @wookoouk 
- [x] GALAXY_CONFIG_BRAND should be configurable
- [ ] The user should be able to choose the Galaxy release
- [ ] maybe a choosen repository should disappear from the search-box?
- [ ] if you change the search term from `gemini` to `vcf` really quick the search will not be triggered
- [x] The search spinner looks a lot like a windows logo, can we just default to the Galaxy one?
- [x] "Your Galaxy will have the following:" should only appear if you have an item
- [x] "Repo" should be renamed to "Source Code"?
- [ ] Linking to the TS would be nice

**Comment by doomedramen** [comment]
All that should be pretty easy to implement. Will do it tomorrow

**Comment by martenson** [comment]
Awesome work.

Using repo search is fine but tool search has its uses. My ideal take would be to incorporate both (maybe using tabs). And when the tool is selected you would query the repo (or I extend the API to provide all info needed) and add it.

**Comment by doomedramen** [comment]
I could have its search both and tag the results as to if they are tools or
repos.

**Comment by martenson** [comment]
I feel they need distinct lists as the search score is not comparable and it would probably create ordering confusion and ux problem.

**Comment by doomedramen** [comment]
Okay, I'll have a crack at it :)

**Comment by martenson** [comment]
@wookoouk Those are just ideas, implement what you want obviously. :)

Btw would you like to transfer your repo under this organization? And what is your thinking regarding licence?

**Comment by doomedramen** [comment]
More than happy to move to Org. I normally go for MIT.

**Comment by doomedramen** [comment]
Updated your checklist (above)

**Comment by jegalle** [comment]
Hi

I just got back from holidays, maybe i should have told you guys.

Had some time to mess around in reactjs and added a 'base image select' where the user is able to select one of @bgruening 's flavors. I've already sent a pull request to @wookoouk .

Hope it helps!

**Comment by martenson** [comment]
@jegalle awesomeness!

**Comment by doomedramen** [comment]
@jegalle :+1:

**Comment by bgruening** [comment]
@jegalle welcome back!

**Comment by bgruening** [comment]
I will close this and create a new one with the checklist.
