### ISSUE TITLE
one-file

### ISSUE THREAD

**Issue by doomedramen** [galaxyFlavorsGenerators/galaxyFlavorGenerator#9]
the build task now generates a file in the root called one-file.html,
this is all the js, css + html compacted into one file, good for iframes, embedding, etc

**Comment by bgruening** [comment]
This works like a charm!

http://htmlpreview.github.io/?https://raw.githubusercontent.com/galaxyFlavorsGenerators/galaxyFlavorGenerator/master/one-file.html
or 
http://bit.ly/galaxy-flavor-generator
